local a = require(script.Parent.Parent.include.RuntimeLib)
local ap = a.import(script, script.Parent.Parent, "utils", "color3").hex
local eh = {
	name = "Dark theme",
	preview = {
		foreground = { color = ColorSequence.new(ap("#ffffff")) },
		background = { color = ColorSequence.new(ap("#232428")) },
		accent = {
			color = ColorSequence.new({
				ColorSequenceKeypoint.new(0, ap("#F6BD29")),
				ColorSequenceKeypoint.new(0.5, ap("#F64229")),
				ColorSequenceKeypoint.new(1, ap("#9029F6")),
			}),
			rotation = 25,
		},
	},
	navbar = {
		outlined = true,
		acrylic = false,
		foreground = ap("#ffffff"),
		background = ap("#232428"),
		transparency = 0,
		accentGradient = {
			color = ColorSequence.new({
				ColorSequenceKeypoint.new(0, ap("#f629c6")),
				ColorSequenceKeypoint.new(0.25, ap("#F64229")),
				ColorSequenceKeypoint.new(0.5, ap("#ffd42a")),
				ColorSequenceKeypoint.new(0.75, ap("#37CC95")),
				ColorSequenceKeypoint.new(1, ap("#3789cc")),
			}),
		},
		dropshadow = ap("#232428"),
		dropshadowTransparency = 0.3,
		glowTransparency = 0,
	},
	clock = {
		outlined = true,
		acrylic = false,
		foreground = ap("#ffffff"),
		background = ap("#232428"),
		transparency = 0,
		dropshadow = ap("#232428"),
		dropshadowTransparency = 0.3,
	},
	home = {
		title = {
			outlined = true,
			acrylic = false,
			foreground = ap("#ffffff"),
			background = ap("#ffffff"),
			backgroundGradient = {
				color = ColorSequence.new({
					ColorSequenceKeypoint.new(0, ap("#F6BD29")),
					ColorSequenceKeypoint.new(0.5, ap("#F64229")),
					ColorSequenceKeypoint.new(1, ap("#9029F6")),
				}),
				rotation = 25,
			},
			transparency = 0,
			dropshadow = ap("#ffffff"),
			dropshadowGradient = {
				color = ColorSequence.new({
					ColorSequenceKeypoint.new(0, ap("#F6BD29")),
					ColorSequenceKeypoint.new(0.5, ap("#F64229")),
					ColorSequenceKeypoint.new(1, ap("#9029F6")),
				}),
				rotation = 25,
			},
			dropshadowTransparency = 0.3,
		},
		profile = {
			outlined = true,
			acrylic = false,
			foreground = ap("#ffffff"),
			background = ap("#232428"),
			transparency = 0,
			dropshadow = ap("#232428"),
			dropshadowTransparency = 0.3,
			avatar = {
				background = ap("#1B1C20"),
				gradient = {
					color = ColorSequence.new({
						ColorSequenceKeypoint.new(0, ap("#F6BD29")),
						ColorSequenceKeypoint.new(0.5, ap("#F64229")),
						ColorSequenceKeypoint.new(1, ap("#9029F6")),
					}),
					rotation = 25,
				},
				transparency = 0,
			},
			button = {
				outlined = true,
				foreground = ap("#ffffff"),
				foregroundTransparency = 0.5,
				background = ap("#1B1C20"),
				backgroundTransparency = 0,
			},
			slider = {
				outlined = true,
				foreground = ap("#ffffff"),
				foregroundTransparency = 0,
				background = ap("#1B1C20"),
				backgroundTransparency = 0,
			},
			highlight = {
				flight = ap("#a22df0"),
				walkSpeed = ap("#EC423D"),
				jumpHeight = ap("#37CC95"),
				refresh = ap("#a22df0"),
				ghost = ap("#FF4040"),
				godmode = ap("#f09c2d"),
				freecam = ap("#37CC95"),
			},
		},
		server = {
			outlined = true,
			acrylic = false,
			foreground = ap("#ffffff"),
			background = ap("#37CC95"),
			transparency = 0,
			dropshadow = ap("#37CC95"),
			dropshadowTransparency = 0.3,
			rejoinButton = {
				outlined = true,
				foreground = ap("#ffffff"),
				background = ap("#37CC95"),
				accent = ap("#232428"),
				foregroundTransparency = 0,
				backgroundTransparency = 0,
			},
			switchButton = {
				outlined = true,
				foreground = ap("#ffffff"),
				background = ap("#37CC95"),
				accent = ap("#232428"),
				foregroundTransparency = 0,
				backgroundTransparency = 0,
			},
		},
		friendActivity = {
			outlined = true,
			acrylic = false,
			foreground = ap("#ffffff"),
			background = ap("#232428"),
			transparency = 0,
			dropshadow = ap("#232428"),
			dropshadowTransparency = 0.3,
			friendButton = {
				outlined = true,
				accent = ap("#37CC95"),
				foreground = ap("#ffffff"),
				foregroundTransparency = 0,
				background = ap("#1B1C20"),
				backgroundTransparency = 0,
				dropshadow = ap("#000000"),
				dropshadowTransparency = 0.4,
				glowTransparency = 0.6,
			},
		},
	},
	apps = {
		players = {
			outlined = true,
			acrylic = false,
			foreground = ap("#ffffff"),
			background = ap("#232428"),
			transparency = 0,
			dropshadow = ap("#232428"),
			dropshadowTransparency = 0.3,
			avatar = {
				background = ap("#1B1C20"),
				gradient = {
					color = ColorSequence.new({
						ColorSequenceKeypoint.new(0, ap("#37CC95")),
						ColorSequenceKeypoint.new(1, ap("#37CC95")),
					}),
					rotation = 25,
				},
				transparency = 0,
			},
			button = {
				outlined = true,
				foreground = ap("#ffffff"),
				foregroundTransparency = 0.5,
				background = ap("#1B1C20"),
				backgroundTransparency = 0,
			},
			highlight = { teleport = ap("#37CC95"), hide = ap("#f09c2d"), kill = ap("#EC423D"), spectate = ap(
				"#a22df0"
			) },
			playerButton = {
				outlined = true,
				accent = ap("#37CC95"),
				foreground = ap("#ffffff"),
				foregroundTransparency = 0.5,
				background = ap("#1B1C20"),
				backgroundTransparency = 0,
				dropshadow = ap("#000000"),
				dropshadowTransparency = 0.5,
				glowTransparency = 0.2,
			},
		},
	},
	options = {
		themes = {
			outlined = true,
			acrylic = false,
			foreground = ap("#ffffff"),
			background = ap("#232428"),
			transparency = 0,
			dropshadow = ap("#232428"),
			dropshadowTransparency = 0.3,
			themeButton = {
				outlined = true,
				accent = ap("#37a4cc"),
				foreground = ap("#ffffff"),
				foregroundTransparency = 0.5,
				background = ap("#1B1C20"),
				backgroundTransparency = 0,
				dropshadow = ap("#000000"),
				dropshadowTransparency = 0.5,
				glowTransparency = 0.2,
			},
		},
		shortcuts = {
			outlined = true,
			acrylic = false,
			foreground = ap("#ffffff"),
			background = ap("#232428"),
			transparency = 0,
			dropshadow = ap("#232428"),
			dropshadowTransparency = 0.3,
			shortcutButton = {
				outlined = true,
				accent = ap("#37CC95"),
				foreground = ap("#ffffff"),
				foregroundTransparency = 0.5,
				background = ap("#1B1C20"),
				backgroundTransparency = 0,
				dropshadow = ap("#000000"),
				dropshadowTransparency = 0.5,
				glowTransparency = 0.2,
			},
		},
		config = {
			outlined = true,
			acrylic = false,
			foreground = ap("#ffffff"),
			background = ap("#232428"),
			transparency = 0,
			dropshadow = ap("#232428"),
			dropshadowTransparency = 0.3,
			configButton = {
				outlined = true,
				accent = ap("#37CC95"),
				foreground = ap("#ffffff"),
				foregroundTransparency = 0.5,
				background = ap("#1B1C20"),
				backgroundTransparency = 0,
				dropshadow = ap("#000000"),
				dropshadowTransparency = 0.5,
				glowTransparency = 0.2,
			},
		},
	},
}
return { darkTheme = eh }
